dependencies:
- name: kube-state-metrics
  version: "2.13.*"
  repository: https://kubernetes.github.io/kube-state-metrics
  condition: kubeStateMetrics.enabled
- name: prometheus-node-exporter
  version: "1.14.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: nodeExporter.enabled
- name: grafana
  version: "6.4.*"
  repository: https://grafana.github.io/helm-charts
  condition: grafana.enabled
