---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-kubedata-unifi-data
  namespace: unifi-controller
  labels:
    volume: unifi-data
spec:
  storageClassName: "managed-nfs-storage"
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.1.53
    path: "/volume1/kubedata/unifi-controller/data"
    readOnly: false
