---
apiVersion: v1
kind: Service
metadata:
  name: unifi-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    app: unifi-controller
  type: LoadBalancer
  loadBalancerIP: 192.168.3.2
  ports:
    - port: 10001
      name: ap-discovery
      targetPort: 10001
      protocol: UDP
    - port: 3478
      name: stun-port
      targetPort: 3478
      protocol: UDP
    - port: 1900
      name: ubnt-1900
      targetPort: 1900
      protocol: UDP
    - port: 5514
      name: ubnt-5514
      targetPort: 5514
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
spec:
  selector:
    app: unifi-controller
  type: LoadBalancer
  loadBalancerIP: 192.168.3.2
  ports:
    - port: 8080
      name: uap-inform
      targetPort: 8080
    - port: 443
      name: controller-gui-api
      targetPort: 8443
    - port: 8880
      name: http-redirect
      targetPort: 8880
    - port: 8843
      name: https-redirect
      targetPort: 8843
    - port: 6789
      name: throughput-measurement
      targetPort: 6789
