apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onepassword-operator-app
spec:
  project: onepassword
  source:
    # The URL of the Helm repository
    repoURL: https://1password.github.io/connect-helm-charts/
    # The name of the Helm Chart
    chart: connect
    # The version of the Helm Chart
    targetRevision: "1.15.0"
    helm:
      # Define the release name (defaults to the name of the ArgoCD application)
      releaseName: onepassword-operator-app
      # Helm values as block file
      # values: |
      #   auth:
      #     username: my-user
      #     password: my-password
  destination:
    server: https://kubernetes.default.svc
    namespace: onepassword
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
