---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: onepassword
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: onepassword
  destinations:
    - namespace: argocd
      server: 'https://kubernetes.default.svc'
    - namespace: 'onepassword'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/FRUCHTiii/homelab_k3s_argocd.git'
    - 'https://1password.github.io/connect-helm-charts/'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'onepassword'
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: onepassword
  source:
    path: onepassword-operator
    repoURL: 'https://github.com/FRUCHTiii/homelab_k3s_argocd.git'
    targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
