---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-kubedata-pihole-dnsmasq
  namespace: pihole
spec:
  storageClassName: "managed-nfs-storage"
  volumeName: pv-nfs-kubedata-pihole-dnsmasq # < The volumename needs correpond with the persistent volume
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: pihole
