---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-kubedata-pihole-dnsmasq  # < Name of the persistent volume
  namespace: pihole
  labels:
    volume: pihole
spec:
  storageClassName: "managed-nfs-storage"
  capacity:
    storage: 10Gi # < Maximum storage size you want to reserve
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.1.53  # < The ip adress of your NAS (NFS Server)
    path: "/volume1/kubedata/pihole/dnsmasq"  # < The NFS volumename
    readOnly: false
