---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: traefik
  destinations:
    - namespace: argocd
      server: 'https://kubernetes.default.svc'
    - namespace: 'kube-system'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/FRUCHTiii/homelab_k3s_argocd.git'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'traefik'
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: traefik
  source:
    path: traefik
    repoURL: 'https://github.com/FRUCHTiii/homelab_k3s_argocd.git'
    targetRevision: 'main'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
