---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-kubedata-pihole
  namespace: pihole
spec:
  storageClassName: ""
  volumeName: pv-nfs-kubedata-pihole # < The volumename needs correpond with the persistent volume
  accessModes:
   - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      volume: pihole
