---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-tcp
spec:
  selector:
    app: homeassistant
  type: LoadBalancer
  loadBalancerIP: 192.168.3.4
  ports:
    - port: 443
      name: hassio-gui-api
      targetPort: 8123
