---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: unifi-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: unifi-controller
  destinations:
    - namespace: argocd
      server: 'https://kubernetes.default.svc'
    - namespace: 'unifi-controller'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/FRUCHTiii/homelab_k3s_argocd.git'
status: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'unifi-controller'
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: unifi-controller
  source:
    path: unifi-controller
    repoURL: 'https://github.com/FRUCHTiii/homelab_k3s_argocd.git'
    targetRevision: 'main'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
