---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '3'
  name: unifi-controller-app
  namespace: argocd
spec:
  destination:
    namespace: unifi-controller
    server: https://kubernetes.default.svc
  project: unifi-controller
  source:
    path: unifi-controller/unifi-controller-app
    repoURL: https://github.com/FRUCHTiii/homelab_k3s_argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
